name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main


permissions:
  contents: write
  id-token: write

concurrency:
  group: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d	# v5.1.0
        with:
          python-version: '3.12'

      - name: Install Poetry and dependencies
        run: |
          pipx install poetry
          poetry install --no-root

      - name: Check for major version
        run: |
          # By default, it's not a major version
          echo "IS_MAJOR_VERSION=false" >> "$GITHUB_ENV"

          # Retrieve the last commit message
          LAST_COMMIT_MESSAGE="$(git log -1 --pretty=%B)"
          echo "Last commit message: $LAST_COMMIT_MESSAGE"
          
          # Search for breaking change in the last commit message
          if echo "$LAST_COMMIT_MESSAGE" | grep -iE "(feat\!|fix\!|breaking change)"; then
            echo "Found breaking change in the last commit message."
            echo "IS_MAJOR_VERSION=true" >> "$GITHUB_ENV"
          fi

      - name: Python Semantic Release
        id: python-semantic-release
        uses: python-semantic-release/python-semantic-release@3ba53469e72452e7597dd5c61851e6fbf294420b # v9.8.5
        with:
          force: ${{ env.IS_MAJOR_VERSION == 'true' && 'major' || ''}}
          github_token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          vcs_release: false

      - name: Print the release details
        run: |
          echo "Released: ${{ steps.python-semantic-release.outputs.released }}"
          echo "Release version: ${{ steps.python-semantic-release.outputs.version }}"
          echo "Release tag: ${{ steps.python-semantic-release.outputs.tag }}"

      - name: Test
        if: steps.python-semantic-release.outputs.released == 'true'
        run: |
          echo "Success! The release was published."

      - name: Publish Release
        run: |
          poetry run semantic-release publish --tag ${{ steps.python-semantic-release.outputs.tag }}

      - name: Print values
        run: |
          echo $GITHUB_PATH
          echo $GITHUB_WORKSPACE
